#!/usr/bin/expect
set timeout 20
spawn /usr/bin/createuser --pwprompt -s root 
expect "Enter password for"
send "vxpass\r"
expect "Enter"
send "vxpass\r" 
send "\n"
spawn createdb -Oroot -Eunicode vx
interact
